### ISSUE TITLE
设置好快高度后，升级剩余的bp节点，报错

### ISSUE THREAD

**Issue by zsq978663747** [eosiosg/eos#13]
版本：eosiosg/dpos-pbft/bos-v0.9.9.2-Release
场景：先用2.0.3版本启动，部分节点升级新的版本，当head到达#1666时升级合约   并且设置3000升级，当剩余的节点没有升级的时候，组成新的网络出块，这时候升级剩余的节点到eosiosg/dpos-pbft/bos-v0.9.9.2-Release，提示如下错误。期间没有加压
节点重启的时候，快高度为#1741 lib：#1330
但是同样情况节点bcd停留在#1680 lib：#1330 bc重启成功，但是d不成功。
![image](https://user-images.githubusercontent.com/32862838/58748236-244e6380-84a8-11e9-9192-e7ca4c205c71.png)

**Comment by zsq978663747** [comment]
刚刚重现了一下，当26个bp只有5个bp没有升级的时候也会出现这个情况

**Comment by oldcold** [comment]
@zsq978663747 can you check if this issue still happens under [bos-v0.9.10](https://github.com/eosiosg/eos/commit/fd444d25fc0b5667fa8d09561576ae56ad2c03ea)

**Comment by zsq978663747** [comment]
bos-v0.9.10版本已经解决
