### ISSUE TITLE
LIB 和LSCB 差距过大，100一个checkpoint 失效

### ISSUE THREAD

**Issue by zsq978663747** [eosiosg/eos#4]
boscore/bos:v3.0.0-rc3

**Comment by qianxiaofeng** [comment]
尝试在bos-v0.9.9 修复, 待测试
docker image: eosiosg/dpos-pbft:bos-bridge-v0.6.8

**Comment by qianxiaofeng** [comment]
需要测试watermark在重启后是否会丢失, 制造某些情况进行测试

**Comment by Frank-AFN** [comment]
> 需要测试watermark在重启后是否会丢失, 制造某些情况进行测试

docker image: eosiosg/dpos-pbft:bos-v0.9.9.2-Release
用7bp在一台机器上和其他bp在集群2测试. 在压力200 TPS 不断投票的环境下. shutdown 7bp 一段时间, 整个网络进入到view change 阶段. lib, lscb 不前进, 不断重启7bp(正常重启和delete-all-blocks) 网络都是可以恢复. 没有出现watermark丢失现象

**Comment by Frank-AFN** [comment]
lib和lscb差距过大 #4 , 网络流量的暴涨 #3 是由于watermark丢失导致的. 

环境: 5bp在一个node上, 2bp down, 其余bp正常. 

watermark缺失:
原因: 在 boscore/bos:v3.0.0-rc3 版本中. watermark是存储在**controller**的vector中, **pbft_\controller**会去从controller中获取current watermark.  当shutdown之后会保存在(pbft_db)磁盘中. 重启后重新从磁盘读取到内存.  由于pbft_controller获取是异步获取. 可能会出现 pbft_controller 中的watermark 和 controller中的watermark不同步的现象. 这时shutdown node, 写入pbft_db中的watermark就会缺失. 

现象: 

1. lib和lscb差距过大 #4
watermark缺失, 导致watermark这一点的checkpoint收不齐. lscb不会前进. 但是此时丢失watermark的bp并不会认为此时的watermark丢失, 因此会继续发高于丢失watermark的prepare commit信息, 因此lib依然会走. 

2. 网络流量的暴涨 #3
整体网络的head高度是 900k, lib高度是800k. bp的lib比较低 head较高, 由于丢失watermark那一点**w**的checkpoint没有收集超过2/3n + 1, peer会不断发送 距 **w**最近的checkpoint 到 lib 的checkpoint. 此时的lscb并不会继续增长.

Solution:
将watermark存储在block_state中, 这样watermark会存储在controller 的 fork_db中, 避免了异步获取watermark丢失的情况. 

https://github.com/eosiosg/eos/blob/a63265fe5b016f6164d3a19480d9cf1a72795ba2/libraries/chain/include/eosio/chain/block_state.hpp#L26

对于网络流量暴涨的优化: 如果检测到缺少**w**点的watermark就不会发送 高于w点的checkpoint.

FIX: - 3c45326
