### ISSUE TITLE
corrupted double-linked list

### ISSUE THREAD

**Issue by zsq978663747** [eosiosg/eos#6]
相同的bp配置，启动了两个nodeos进程，先启动的那个nodeos 出现“corrupted double-linked list” log crash.

**Comment by Frank-AFN** [comment]
这个crash已经基本定位和free()  malloc() crash是类似的问题. 是在收块, 然后start_block里发生exception, 在释放try中资源的时候crash.

**Comment by qianxiaofeng** [comment]
长期观察一下, 需要尝试找出稳定复现的方法

**Comment by Frank-AFN** [comment]
This issue is similar to #14. Track #14 instead.
